### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by shawnjun21** [aren-cllc/DiscordMonies#2]
Hello,
I'm really interested in your bot and wanted to invite it to my discord server. I've done everything in your installation instructions but I am facing some problems... I am using Visual Studio Code on a MacBook Air.

These were your instructions:
1. Clone the repository using git clone https://github.com/aren-cllc/DiscordMonies.git
2. Create a file called data.json, and put {"token":"yourtokenhere"} into that file, replacing yourtokenhere with your bot's token.
3. Install discord.js with npm install --save discord.js
4. Run bot.js with node bot.js

After doing all of the above, I ran node bot.js and terminal said

module.js:557
    throw err;
    ^

Error: Cannot find module 'array-next'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/sjun21/DiscordMonies/classes/structures/game.js:2:12)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)

Then I did npm install array-next and tried doing node bot.js again but I got:

(node:1230) UnhandledPromiseRejectionWarning: Error: An invalid token was provided.
    at Promise (/Users/sjun21/DiscordMonies/node_modules/discord.js/src/client/rest/RESTMethods.js:33:44)
    at new Promise (<anonymous>)
    at RESTMethods.login (/Users/sjun21/DiscordMonies/node_modules/discord.js/src/client/rest/RESTMethods.js:32:12)
    at Client.login (/Users/sjun21/DiscordMonies/node_modules/discord.js/src/client/Client.js:277:30)
    at Object.<anonymous> (/Users/sjun21/DiscordMonies/bot.js:160:8)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
(node:1230) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1230) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I don't know what this means. I apologize, for I am new to coding and creating Discord bots. I hope you can help me.

Thank you,
shawnjun21

**Comment by shawnjun21** [comment]
``

**Comment by colorfulchair** [comment]
Hey, this project is very old and not supported. I recommend looking at vicr123/leisurebot because it is way more developed and Discord Monies is built in.

**Comment by colorfulchair** [comment]
Anyway, the token you provided was incorrect.

**Comment by shawnjun21** [comment]
Thank you very much!
